name:                nullification
version:             0.1.0.0
github:              "isovector/nullification"
license:             BSD3
author:              "Sandy Maguire"
maintainer:          "sandy@sandymaguire.me"
copyright:           "2020 Sandy Maguire"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/isovector/nullification#readme>

dependencies:
- base-noprelude >= 4.7 && < 5
- base-prelude
- lens
- transformers
- containers
- mtl
- sequoia
- linear
- frpnow
- ecstasy
- monad-coroutine
- sdl2-mixer
- sdl2
- binary
- generic-lens

default-extensions:
- DataKinds
- FlexibleContexts
- GADTs
- LambdaCase
- PolyKinds
- RankNTypes
- ScopedTypeVariables
- TypeApplications
- TypeOperators
- TypeFamilies
- DeriveGeneric
- DerivingStrategies
- DerivingVia
- DeriveDataTypeable
- DeriveFoldable
- DeriveTraversable
- DeriveFunctor
- BangPatterns
- FlexibleInstances

library:
  source-dirs: src

executables:
  nullification-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - nullification

tests:
  nullification-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - nullification
